import {
  Heart,
  Activity,
  Brain,
  Bone,
  Baby,
  Ear,
  Eye,
  Stethoscope,
  Syringe,
  Pill,
  Microscope,
  ScanSearch,
  Video,
  Calendar,
  Droplet,
  Ambulance,
  Building2,
  Scissors,
  Thermometer,
  TestTube,
  X,
  Car,
  Wifi,
  Accessibility,
  Shield,
  Siren,
  CreditCard,
  Monitor,
  Hospital,
  Sparkles,
  Zap,
  Sun,
  Moon,
  Cloud,
  Snowflake,
  Wind,
  Flame,
  Leaf,
  Flower2,
  TreePine,
  Mountain,
  Waves,
  Footprints,
  User,
  Users,
  UserPlus,
  UserCheck,
  Mail,
  Phone,
  MapPin,
  MessageCircle,
  Home,
  Store,
  Factory,
  Landmark,
  School,
  GraduationCap,
  BookOpen,
  Briefcase,
  ClipboardList,
  FileText,
  Folder,
  Archive,
  Search,
  Filter,
  Settings,
  Bell,
  Clock,
  Timer,
  Check,
  XCircle,
  AlertCircle,
  Info,
  HelpCircle,
  Star,
  Award,
  Target,
  Flag,
  Trophy,
  Gift,
  ShoppingCart,
  Package,
  Truck,
  Plane,
  Ship,
  Bike,
  Bus,
  Train,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  heart: Heart,
  activity: Activity,
  brain: Brain,
  bone: Bone,
  baby: Baby,
  ear: Ear,
  eye: Eye,
  stethoscope: Stethoscope,
  syringe: Syringe,
  pill: Pill,
  microscope: Microscope,
  "scan-search": ScanSearch,
  video: Video,
  calendar: Calendar,
  droplet: Droplet,
  ambulance: Ambulance,
  "building-2": Building2,
  scissors: Scissors,
  thermometer: Thermometer,
  "test-tube": TestTube,
  x: X,
  car: Car,
  wifi: Wifi,
  accessibility: Accessibility,
  shield: Shield,
  siren: Siren,
  "credit-card": CreditCard,
  monitor: Monitor,
  hospital: Hospital,
  sparkles: Sparkles,
  zap: Zap,
  sun: Sun,
  moon: Moon,
  cloud: Cloud,
  snowflake: Snowflake,
  wind: Wind,
  flame: Flame,
  leaf: Leaf,
  flower2: Flower2,
  "tree-pine": TreePine,
  mountain: Mountain,
  waves: Waves,
  footprints: Footprints,
  user: User,
  users: Users,
  "user-plus": UserPlus,
  "user-check": UserCheck,
  mail: Mail,
  phone: Phone,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  home: Home,
  store: Store,
  factory: Factory,
  landmark: Landmark,
  school: School,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  briefcase: Briefcase,
  "clipboard-list": ClipboardList,
  "file-text": FileText,
  folder: Folder,
  archive: Archive,
  search: Search,
  filter: Filter,
  settings: Settings,
  bell: Bell,
  clock: Clock,
  timer: Timer,
  check: Check,
  "x-circle": XCircle,
  "alert-circle": AlertCircle,
  info: Info,
  "help-circle": HelpCircle,
  star: Star,
  award: Award,
  target: Target,
  flag: Flag,
  trophy: Trophy,
  gift: Gift,
  "shopping-cart": ShoppingCart,
  package: Package,
  truck: Truck,
  plane: Plane,
  ship: Ship,
  bike: Bike,
  bus: Bus,
  train: Train,
};

const ALL_ICON_KEYS = Object.keys(iconMap).filter(Boolean);

export const ICON_OPTIONS = [
  { value: "", label: "" },
  ...ALL_ICON_KEYS.map((v) => ({ value: v, label: "" })),
];

export function getIcon(name: string | null): LucideIcon | null {
  if (!name) return null;
  const key = name.toLowerCase().replace(/\s+/g, "-");
  return iconMap[key] ?? null;
}
